### PR TITLE
Replace anchore/inline-scan with anchore/anchore-engine

### PR DESCRIPTION
**Pull request by airadier**
The anchore/inline-scan is the anchore/anchore-engine plus Postgres and a more than 5GB vulnerability database which is not used at all, as the evaluation is done in the backend.

This PR replaces anchore/inline-scan with anchore/anchore-engine and adapts the container creating command to run exactly the same analysis (metadata extraction) using the lighter container.

The RUN_CMD variable has been removed, as it is unused.

### CODE REVIEW

**Comment by airadier** [comment]
Please @marojor check, as we were commenting about this today. @ProvoK .

**Comment by marojor** [comment]
@airadier Looks good to me, let me run the tests with this branch and get back here with results before merging it.

**Review by mattpag — APPROVED** [review]

**Review by ProvoK — APPROVED** [review]
LGTM @marojor let us know if the QA tests pass, it works from what I've manually tested

**Review by marojor — APPROVED** [review]
Changes LGTM and automated tests run successfully.

No performance impact other than the size of the image, which I guess confirms the idea that both images are actually running the same code.

**Pull request merged**
